# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Slack WebHook

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: wei/curl@v1
        with:
          args: -X POST --data '{"text":"Yohooo, mousaillon ! Une nouvelle version de royal fortune est disponible!
          Voici une reconstitution de la dernière traversé du Royal Fortune réalisée par notre meilleur matelo peintre:\n
          https://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@raw.githubusercontent.com/pns-si3-qgl/qgl-21-22-royal_fortune/develop/tooling/webtool/webtool/uploads/lastRun.png"}' https://hooks.slack.com/services/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





