# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Curl Slack WebHook

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
      - name: REST API with curl
        run: |
              curl -X POST --data '{"text":"Yohoo, mousaillon ! Une nouvelle version de royal fortune est disponible!\nVoici une reconstitution de la dernière traversé du Royal Fortune réalisée par notre meilleur matelo peintre:\n https://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@raw.githubusercontent.com/pns-si3-qgl/qgl-21-22-royal_fortune/develop/tooling/webtool/webtool/uploads/lastRun.png"}' https://hooks.slack.com/services/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